//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CherkashinProject.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class linecoreBaseEntities : DbContext
    {
        public linecoreBaseEntities()
            : base("name=linecoreBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<GetTovara> GetTovara { get; set; }
        public virtual DbSet<Kontragent> Kontragent { get; set; }
        public virtual DbSet<PostTovara> PostTovara { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TovarColor> TovarColor { get; set; }
        public virtual DbSet<Tovares> Tovares { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
